name: Docker build and push to azure storage

on:
  push:
    branches:
      - 'master'

jobs:
  production-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PRD }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build and push to storage account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            npm install --global yarn && ./scripts/ci_build_deploy.sh && az storage blob upload-batch --overwrite --account-name darkforestprod --auth-mode key -d '$web' -s "client/dist"
      
      - name: logout
        run: |
          az logout
        if: always()

